name: GitHub Workflow test


on:
  workflow_dispatch:

jobs:
  test:
    name: GitHub example
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
    steps:
      - run: |
          echo "Fruit $fruit, Animal $animal, Color $color, Shape $shape"
