name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.6"
          - "1"
        include:
          - version: nightly
            allow_failure: true
          - version: 1
            allow_failure: true
    steps:
      - run: |
          echo "Version ${{ matrix.version }}, allow_failure=${{ matrix.allow_failure }}"
